-- Agrega el DNI real de la persona al Cliente Final.
-- No tiene relación con "cuenta.dni_alta_sensa" (identificador sintético que
-- exige SENSA para el alta de la Cuenta): este campo es sólo un dato
-- administrativo local de la Empresa Revendedora y nunca se envía al Proveedor.
--
-- CORREGIDA el 27/08/2026: el intento original agregaba la columna NOT NULL
-- asumiendo una tabla vacía, pero producción ya tenía Clientes Finales
-- cargados sin este dato. Postgres rechazó el ALTER (P3009 en Prisma) y la
-- migración nunca llegó a aplicarse en ningún ambiente, así que se corrige
-- directo acá en vez de sumar una migración nueva. Los Clientes Finales
-- históricos quedan con `dni = NULL` hasta que alguien los complete a mano
-- desde el panel (PATCH /customers/:id); el alta nueva lo sigue exigiendo
-- desde el DTO (`CrearClienteDto.dni`).
ALTER TABLE "cliente_final" ADD COLUMN "dni" VARCHAR(20);
